### ISSUE TITLE
Can't run with new `openapi-spec-validator==0.5.0`

### ISSUE THREAD

**Issue by Wim-De-Clercq** [Pylons/pyramid_openapi3#173]
dependency tree on a clean install:
```
pyramid-openapi3==0.14
  - openapi-core [required: >=0.13.4,<0.14, installed: 0.13.8]
    - openapi-spec-validator [required: Any, installed: 0.5.0]
  - openapi-spec-validator [required: Any, installed: 0.5.0]
```
The error is actually within `openapi-core`
```
    from openapi_core.unmarshalling.schemas.formatters import Formatter
../.venv/lib/python3.8/site-packages/openapi_core/__init__.py:3: in <module>
    from openapi_core.shortcuts import (
../.venv/lib/python3.8/site-packages/openapi_core/shortcuts.py:3: in <module>
    from openapi_core.schema.shortcuts import create_spec
../.venv/lib/python3.8/site-packages/openapi_core/schema/shortcuts.py:3: in <module>
    from openapi_spec_validator import (
E   ImportError: cannot import name 'default_handlers' from 'openapi_spec_validator' (/home/wim/projects/onroerend-erfgoed/premieaanvragen-old/.venv/lib/python3.8/site-packages/openapi_spec_validator/__init__.py)
```
And this is also fixed in openapi-core 0.14.5
But `pyramid_openapi3` can't work with >= 0.14.0, so you are left with an incompatible library tree on installation.

The only workaround right now is to pin `openapi-spec-validator==0.4.0` when installing pyramid_openapi3.

**Comment by zupo** [comment]
I can take a look next week if noone beats me to it.

**Comment by claeyswo** [comment]
Is there any update on this?

**Comment by zupo** [comment]
No, sorry, haven't had the time to look at it yet, and likely will not be able until next month.
